import assert from 'node:assert/strict';import test from 'node:test';import {v63TrustSchema} from '../src/v63-schema';import {buildAttestationChainV63,scoreProvenanceTrustV63,simulateGovernancePoliciesV63,buildChangeAuthorizationEnvelopesV63,checkSegregationOfDutiesV63,evaluateApprovalQuorumV63,mapComplianceControlsV63,evaluateWaiverGovernanceV63,propagateEvidenceFreshnessInvalidationV63,verifyArtifactIntegrityContractsV63,compileGovernanceAuditTrailV63,scoreRuntimeTrustV63,analyzeDeploymentAuthorizationV63,buildReleaseGovernancePacketsV63,auditAttestationCompletenessV63,evaluateControlEvidenceSufficiencyV63,buildGovernanceHealthV63,auditTrustGovernanceConsistencyV63,buildTrustGovernanceSnapshotV63} from '../src/v63-engine';
const base=()=>v63TrustSchema.parse({objective:'govern release',evidence:[{id:'e1',verified:true,fresh:true,confidence:95,artifactHash:'h'}],attestations:[{id:'a1',evidenceId:'e1',issuer:'ci',verified:true,signatureObserved:true}],actors:[{id:'requester',roles:['dev']},{id:'approver1',roles:['reviewer']},{id:'approver2',roles:['reviewer']}],approvals:[{id:'ap1',actorId:'approver1',actionId:'c1',approved:true},{id:'ap2',actorId:'approver2',actionId:'c1',approved:true}],changes:[{id:'c1',kind:'DEPLOY',risk:30,requester:'requester',approver:'approver1',evidenceRefs:['e1']}],policies:[{id:'p',actionKind:'DEPLOY',effect:'REQUIRE_APPROVAL',priority:10}],controls:[{id:'ctrl',framework:'internal',requirement:'verified evidence',evidenceRefs:['e1']}],artifacts:[{id:'art',hash:'abc',expectedHash:'abc',verified:true}],releases:[{id:'r1',changeIds:['c1'],risk:20,requestedBy:'requester'}],requiredApprovalCount:2});
test('attestation chain does not claim signature',()=>assert.equal(buildAttestationChainV63(base()).signatureClaim,false));
test('provenance trust high',()=>assert.ok(scoreProvenanceTrustV63(base()).evidence[0].score>80));
test('policy simulation non-executing',()=>assert.equal(simulateGovernancePoliciesV63(base()).changes[0].executed,false));
test('authorization envelope has evidence and SoD',()=>{const r=buildChangeAuthorizationEnvelopesV63(base()).changes[0];assert.equal(r.evidenceReady,true);assert.equal(r.separationOk,true)});
test('SoD baseline clean',()=>assert.equal(checkSegregationOfDutiesV63(base()).violations.length,0));
test('approval quorum met',()=>assert.equal(evaluateApprovalQuorumV63(base()).actions[0].quorum,true));
test('control mapping covered',()=>assert.equal(mapComplianceControlsV63(base()).controls[0].covered,true));
test('no active waivers baseline',()=>assert.equal(evaluateWaiverGovernanceV63(base()).waivers.length,0));
test('freshness baseline clean',()=>assert.equal(propagateEvidenceFreshnessInvalidationV63(base()).stale.length,0));
test('artifact integrity verified',()=>assert.equal(verifyArtifactIntegrityContractsV63(base()).artifacts[0].integrity,true));
test('audit trail non-persistent',()=>assert.equal(compileGovernanceAuditTrailV63(base()).persistenceClaim,false));
test('runtime trust positive',()=>assert.ok(scoreRuntimeTrustV63(base()).score>70));
test('deployment authorization true from supplied approvals',()=>assert.equal(analyzeDeploymentAuthorizationV63(base()).releases[0].authorized,true));
test('release packet reflects authorization',()=>assert.equal(buildReleaseGovernancePacketsV63(base()).packets[0].authorization,true));
test('attestation complete',()=>assert.deepEqual(auditAttestationCompletenessV63(base()).attested,['e1']));
test('control evidence sufficient',()=>assert.equal(evaluateControlEvidenceSufficiencyV63(base()).controls[0].sufficient,true));
test('governance health trust',()=>assert.ok(buildGovernanceHealthV63(base()).trust.score>70));
test('consistency clean',()=>assert.equal(Object.values(auditTrustGovernanceConsistencyV63(base())).flat().length,0));
test('snapshot ready and bounded',()=>{const r=buildTrustGovernanceSnapshotV63(base());assert.equal(r.status,'READY');assert.equal(r.executionClaim,false);assert.equal(r.certificationClaim,false)});
