import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';

export const HASH_CONTRACT = 'krom-instruction-raw-utf8-v1' as const;
export const LEGACY_STATUS = 'LEGACY_UNPROVEN' as const;
const root = path.resolve(process.cwd());
const sha256=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');
const legacySource='KROM Forge v4.2 supplied manifest.json; retained without revalidation';

type Legacy={name:string;relativePath:string;instructionHash:string;rawFileHash:string};
function parseLegacy(source:string):Legacy[]{
  const rows:Legacy[]=[]; const re=/\{"name":"([^"]+)","relativePath":"([^"]+)","instructionHash":"([a-f0-9]{64})","rawFileHash":"([a-f0-9]{64})"\}/g;
  for(const match of source.matchAll(re)) rows.push({name:match[1],relativePath:match[2],instructionHash:match[3],rawFileHash:match[4]});
  if(rows.length!==500) throw new Error(`LEGACY_MANIFEST_COUNT:${rows.length}`);
  return rows;
}
function assertUtf8(bytes:Buffer,name:string):string{
  let text:string; try { text=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(bytes); } catch { throw new Error(`INVALID_UTF8:${name}`); }
  const roundTrip=Buffer.from(text,'utf8'); if(!roundTrip.equals(bytes)) throw new Error(`UTF8_ROUNDTRIP_MISMATCH:${name}`);
  return text;
}
function metadata(entry:Legacy,instructionHash:string,bytes:number){ return {name:entry.name,version:'4.3.0',hashContract:HASH_CONTRACT,instructionHash,rawFileHash:instructionHash,legacyInstructionHash:entry.instructionHash,legacyInstructionHashStatus:LEGACY_STATUS,legacyInstructionHashSource:legacySource,bytes}; }

export async function generate(){
  const legacy=parseLegacy(await fs.readFile(path.join(root,'src/v80-v42-instruction-manifest.ts'),'utf8'));
  const excluded=new Set(['supabase-security-boundaries']); const entries=[]; const vectors=[];
  for(const entry of legacy.sort((a,b)=>a.name.localeCompare(b.name))){
    if(excluded.has(entry.name)) continue;
    const bytes=await fs.readFile(path.join(root,entry.relativePath)); assertUtf8(bytes,entry.name); const h=sha256(bytes);
    entries.push({name:entry.name,relativePath:entry.relativePath,instructionHash:h,rawFileHash:h,hashContract:HASH_CONTRACT,legacyInstructionHash:entry.instructionHash,legacyInstructionHashStatus:LEGACY_STATUS,legacyInstructionHashSource:legacySource});
    vectors.push({name:entry.name,bytes:bytes.length,hexPrefix:bytes.subarray(0,16).toString('hex'),instructionHash:h});
    await fs.writeFile(path.join(root,entry.relativePath.replace(/SKILL\.md$/,'metadata.v4.3.json')),JSON.stringify(metadata(entry,h,bytes.length),null,2)+'\n');
  }
  if(entries.length!==500) throw new Error(`V43_COUNT:${entries.length}`);
  const header='// Deterministically generated by scripts/generate-v80-v43-instruction-pack.ts. Do not hand-edit.\n';
  const type='export type V80V43InstructionManifestEntry = Readonly<{name:string;relativePath:string;instructionHash:string;rawFileHash:string;hashContract:"krom-instruction-raw-utf8-v1";legacyInstructionHash:string;legacyInstructionHashStatus:"LEGACY_UNPROVEN";legacyInstructionHashSource:string}>;\n';
  await fs.writeFile(path.join(root,'src/v80-v43-instruction-manifest.ts'),header+type+'export const V80_V43_INSTRUCTION_MANIFEST:readonly V80V43InstructionManifestEntry[] = '+JSON.stringify(entries,null,2)+' as const;\n');
  await fs.mkdir(path.join(root,'artifacts'),{recursive:true}); await fs.writeFile(path.join(root,'artifacts/v80-v43-instruction-test-vectors.json'),JSON.stringify({hashContract:HASH_CONTRACT,algorithm:'SHA-256',input:'exact original SKILL.md bytes',transformation:'none',vectors},null,2)+'\n');
  return {count:entries.length,hashContract:HASH_CONTRACT};
}
if(import.meta.url===`file://${process.argv[1]}`) generate().then(x=>console.log(JSON.stringify(x))).catch(error=>{console.error(error);process.exitCode=1;});
