import assert from 'node:assert/strict';
import { v71ContinuousAssuranceSchema } from '../src/v71-schema';
import { assessVerificationDebtV71, measureEvidenceEntropyV71, compareTelemetryBaselineV71, allocateAnomalyBudgetV71, buildRegressionRiskMapV71, scoreAssuranceConfidenceDeltaV71, buildLearningFeedbackV71, buildContinuousAssuranceSnapshotV71 } from '../src/v71-engine';
const i=v71ContinuousAssuranceSchema.parse({objective:'v71 continuous assurance benchmark',nowEpoch:2000,evidence:[{id:'e-check',verified:true,fresh:true,confidence:95,observedAtEpoch:1900,kind:'CHECK'},{id:'e-base',verified:true,fresh:true,confidence:96,observedAtEpoch:1800,kind:'BASELINE'},{id:'e-now',verified:true,fresh:true,confidence:97,observedAtEpoch:1950,kind:'TELEMETRY'},{id:'e-outcome',verified:true,fresh:true,confidence:94,observedAtEpoch:1980,kind:'OUTCOME'}],services:[{name:'api',criticality:70}],checks:[{id:'c1',domain:'runtime',passed:true,severity:80,service:'api',lastPassedEpoch:1950,evidenceRefs:['e-check']}],regressions:[],baselines:[{service:'api',errorRate:0.2,latencyMs:100,availability:99.99,observedAtEpoch:1800,evidenceRefs:['e-base']}],currentTelemetry:[{service:'api',errorRate:0.3,latencyMs:120,availability:99.98,observedAtEpoch:1950,evidenceRefs:['e-now']}],outcomes:[{id:'o1',kind:'release',success:true,service:'api',evidenceRefs:['e-outcome']}]});
assert.equal(assessVerificationDebtV71(i).pass,true);assert.equal(measureEvidenceEntropyV71(i).pass,true);assert.equal(compareTelemetryBaselineV71(i).pass,true);assert.equal(allocateAnomalyBudgetV71(i).pass,true);assert.equal(buildRegressionRiskMapV71(i).pass,true);assert.equal(scoreAssuranceConfidenceDeltaV71(i).band,'HIGH');assert.equal(buildLearningFeedbackV71(i).coverage,100);assert.equal(buildContinuousAssuranceSnapshotV71(i).status,'READY');
const stale=v71ContinuousAssuranceSchema.parse({...i,nowEpoch:100000,evidence:i.evidence.map(e=>({...e,observedAtEpoch:1}))});assert.equal(measureEvidenceEntropyV71(stale).pass,false);assert.equal(buildContinuousAssuranceSnapshotV71(stale).status,'BLOCKED');
const regression=v71ContinuousAssuranceSchema.parse({...i,regressions:[{id:'r1',service:'api',risk:90,active:true,evidenceRefs:['e-now']}]});assert.equal(buildRegressionRiskMapV71(regression).pass,false);
const debt=v71ContinuousAssuranceSchema.parse({...i,checks:[{...i.checks[0],passed:false}]});assert.equal(assessVerificationDebtV71(debt).pass,false);
console.log(JSON.stringify({status:'PASS',verificationDebt:true,evidenceEntropy:true,telemetryBaseline:true,anomalyBudget:true,regressionRisk:true,confidenceDelta:true,learningFeedback:true,continuousSnapshot:true},null,2));
