import { z } from 'zod';
const sev={CRITICAL:4,HIGH:3,MEDIUM:2,LOW:1} as const;
const uniq=<T,>(v:T[])=>[...new Set(v)];

export const portfolioItemSchema=z.object({id:z.string(),name:z.string(),priority:z.enum(['CRITICAL','HIGH','MEDIUM','LOW']).default('MEDIUM'),status:z.enum(['PLANNED','ACTIVE','BLOCKED','AT_RISK','COMPLETE','UNKNOWN']).default('UNKNOWN'),dependencies:z.array(z.string()).default([]),requiredCapabilities:z.array(z.string()).default([]),blockers:z.array(z.string()).default([]),risks:z.array(z.object({id:z.string(),severity:z.enum(['CRITICAL','HIGH','MEDIUM','LOW']),description:z.string()})).default([]),evidenceRefs:z.array(z.string()).default([])});
export const portfolioModelSchema=z.object({portfolioId:z.string(),name:z.string(),items:z.array(portfolioItemSchema).default([]),constraints:z.array(z.string()).default([]),evidenceRefs:z.array(z.string()).default([])});
export const portfolioScenarioSchema=z.object({portfolio:portfolioModelSchema,changedItemIds:z.array(z.string()).default([]),unavailableCapabilities:z.array(z.string()).default([]),newConstraints:z.array(z.string()).default([])});
export const comparePortfoliosSchema=z.object({before:portfolioModelSchema,after:portfolioModelSchema});
type Portfolio=z.infer<typeof portfolioModelSchema>;
export function auditPortfolio(p:Portfolio){const ids=p.items.map(x=>x.id),duplicates=uniq(ids.filter((x,i)=>ids.indexOf(x)!==i)),dangling=p.items.flatMap(i=>i.dependencies.filter(d=>!ids.includes(d)).map(d=>`${i.id}->${d}`)),unsupportedComplete=p.items.filter(i=>i.status==='COMPLETE'&&!i.evidenceRefs.length).map(i=>i.id);return{healthy:!duplicates.length&&!dangling.length&&!unsupportedComplete.length,duplicates,danglingDependencies:dangling,unsupportedComplete};}
export function buildPortfolioDependencyGraph(p:Portfolio){return{nodes:p.items.map(i=>({id:i.id,name:i.name,status:i.status,priority:i.priority})),edges:p.items.flatMap(i=>i.dependencies.map(d=>({from:d,to:i.id,type:'DEPENDS_ON'})))};}
export function detectPortfolioBottlenecks(p:Portfolio){const m=new Map<string,string[]>();for(const i of p.items)for(const c of i.requiredCapabilities){const a=m.get(c)??[];a.push(i.id);m.set(c,a)}return{capabilityBottlenecks:[...m].filter(([,v])=>v.length>1).map(([capability,items])=>({capability,items})),fanOut:p.items.map(i=>({id:i.id,dependents:p.items.filter(x=>x.dependencies.includes(i.id)).map(x=>x.id)})).filter(x=>x.dependents.length>1),blocked:p.items.filter(i=>i.blockers.length||i.status==='BLOCKED').map(i=>i.id)};}
export function prioritizePortfolio(p:Portfolio){return{ordered:p.items.map(i=>{const risk=Math.max(0,...i.risks.map(r=>sev[r.severity])),priority={CRITICAL:4,HIGH:3,MEDIUM:2,LOW:1}[i.priority],impact=p.items.filter(x=>x.dependencies.includes(i.id)).length,evidencePenalty=i.evidenceRefs.length?0:1;return{id:i.id,name:i.name,attentionIndex:priority*3+risk*2+impact+evidencePenalty,factors:{priority,risk,impact,evidencePenalty}}}).sort((a,b)=>b.attentionIndex-a.attentionIndex),rule:'Attention index is an operational triage aid, not a business-value verdict.'};}
export function assessPortfolioScenario(input:z.infer<typeof portfolioScenarioSchema>){const impacted=new Set(input.changedItemIds);let changed=true;while(changed){changed=false;for(const i of input.portfolio.items)if(i.dependencies.some(d=>impacted.has(d))&&!impacted.has(i.id)){impacted.add(i.id);changed=true}}const capabilityImpacted=input.portfolio.items.filter(i=>i.requiredCapabilities.some(c=>input.unavailableCapabilities.includes(c))).map(i=>i.id);return{impactedItems:[...impacted],capabilityImpacted,newConstraints:input.newConstraints,requiresReplan:impacted.size>0||capabilityImpacted.length>0||input.newConstraints.length>0};}
export function buildPortfolioCommandBrief(p:Portfolio){return{portfolioId:p.portfolioId,audit:auditPortfolio(p),bottlenecks:detectPortfolioBottlenecks(p),attention:prioritizePortfolio(p).ordered.slice(0,5)};}
export function comparePortfolios(before:Portfolio,after:Portfolio){const b=new Map(before.items.map(i=>[i.id,i])),a=new Map(after.items.map(i=>[i.id,i]));return{added:[...a.keys()].filter(x=>!b.has(x)),removed:[...b.keys()].filter(x=>!a.has(x)),statusChanges:[...a.values()].filter(x=>b.has(x.id)&&b.get(x.id)!.status!==x.status).map(x=>({id:x.id,before:b.get(x.id)!.status,after:x.status})),blockerDelta:after.items.reduce((n,i)=>n+i.blockers.length,0)-before.items.reduce((n,i)=>n+i.blockers.length,0)};}

export const pipelineStageSchema=z.object({id:z.string(),name:z.string(),kind:z.enum(['BUILD','TEST','SECURITY','COMPLIANCE','PACKAGE','DEPLOY','VERIFY','APPROVAL','OTHER']),status:z.enum(['PASS','FAIL','RUNNING','SKIPPED','UNKNOWN']),required:z.boolean().default(true),dependsOn:z.array(z.string()).default([]),evidenceRefs:z.array(z.string()).default([]),retryCount:z.number().int().nonnegative().default(0),allowsFailure:z.boolean().default(false),mutatesProduction:z.boolean().default(false)});
export const pipelineModelSchema=z.object({pipelineId:z.string(),commitRef:z.string().default(''),environment:z.enum(['LOCAL','CI','PREVIEW','STAGING','PRODUCTION']).default('CI'),stages:z.array(pipelineStageSchema).default([]),rollbackConfigured:z.boolean().default(false),artifactImmutable:z.boolean().default(false),provenanceRefs:z.array(z.string()).default([])});
export const pipelineHistorySchema=z.object({runs:z.array(z.object({runId:z.string(),status:z.enum(['PASS','FAIL','UNKNOWN']),failedStageIds:z.array(z.string()).default([]),evidenceRefs:z.array(z.string()).default([])})).default([])});
export const comparePipelinesSchema=z.object({before:pipelineModelSchema,after:pipelineModelSchema});
type Pipeline=z.infer<typeof pipelineModelSchema>;
export function auditPipeline(p:Pipeline){const ids=p.stages.map(s=>s.id),duplicates=uniq(ids.filter((x,i)=>ids.indexOf(x)!==i)),dangling=p.stages.flatMap(s=>s.dependsOn.filter(d=>!ids.includes(d)).map(d=>`${s.id}->${d}`)),unsupportedPass=p.stages.filter(s=>s.required&&s.status==='PASS'&&!s.evidenceRefs.length).map(s=>s.id),unsafeProd=p.stages.filter(s=>s.mutatesProduction&&s.allowsFailure).map(s=>s.id);return{healthy:!duplicates.length&&!dangling.length&&!unsupportedPass.length&&!unsafeProd.length,duplicates,dangling,unsupportedPass,unsafeProd};}
export function evaluatePipelineGate(p:Pipeline){const a=auditPipeline(p),required=p.stages.filter(s=>s.required),blockers=uniq([...required.filter(s=>s.status==='FAIL'||s.status==='UNKNOWN'||s.status==='RUNNING').map(s=>s.id),...a.unsupportedPass,...a.unsafeProd,...a.dangling]);if(p.environment==='PRODUCTION'&&!p.rollbackConfigured)blockers.push('Production pipeline has no rollback configuration.');if(p.environment==='PRODUCTION'&&!p.artifactImmutable)blockers.push('Production artifact immutability is not evidenced.');return{status:blockers.length?'BLOCKED':'PASS',blockers};}
export function detectWeakPipelineGates(p:Pipeline){return{missingSecurityGate:!p.stages.some(s=>s.kind==='SECURITY'&&s.required),missingTestGate:!p.stages.some(s=>s.kind==='TEST'&&s.required),missingVerifyGate:!p.stages.some(s=>s.kind==='VERIFY'&&s.required),retryHotspots:p.stages.filter(s=>s.retryCount>=2).map(s=>s.id)};}
export function analyzePipelineFailurePatterns(h:z.infer<typeof pipelineHistorySchema>){const m=new Map<string,number>();for(const r of h.runs)for(const id of r.failedStageIds)m.set(id,(m.get(id)??0)+1);return{runs:h.runs.length,failures:h.runs.filter(r=>r.status==='FAIL').length,topFailureStages:[...m].map(([stageId,count])=>({stageId,count})).sort((a,b)=>b.count-a.count),unsupportedPasses:h.runs.filter(r=>r.status==='PASS'&&!r.evidenceRefs.length).map(r=>r.runId)};}
export function buildPipelineHardeningPlan(p:Pipeline){const w=detectWeakPipelineGates(p),actions:string[]=[];if(w.missingTestGate)actions.push('Add required test gate with evidence.');if(w.missingSecurityGate)actions.push('Add required security gate with evidence.');if(w.missingVerifyGate)actions.push('Add post-deploy runtime verification gate.');if(p.environment==='PRODUCTION'&&!p.rollbackConfigured)actions.push('Add verified rollback path.');if(!p.artifactImmutable)actions.push('Use immutable promotion artifact.');return{status:actions.length?'HARDENING_REQUIRED':'BASELINE_OK',actions,weaknesses:w};}
export function buildPipelineEvidenceManifest(p:Pipeline){return{pipelineId:p.pipelineId,commitRef:p.commitRef,environment:p.environment,stages:p.stages.map(s=>({id:s.id,kind:s.kind,status:s.status,evidenceRefs:s.evidenceRefs})),provenanceRefs:p.provenanceRefs,gate:evaluatePipelineGate(p)};}
export function comparePipelines(before:Pipeline,after:Pipeline){return{gate:{before:evaluatePipelineGate(before),after:evaluatePipelineGate(after)},rollback:{before:before.rollbackConfigured,after:after.rollbackConfigured},immutableArtifact:{before:before.artifactImmutable,after:after.artifactImmutable}};}

export const failureScenarioSchema=z.object({id:z.string(),title:z.string(),severity:z.enum(['CRITICAL','HIGH','MEDIUM','LOW']),affectedAssets:z.array(z.string()).default([]),existingControls:z.array(z.string()).default([]),controlEvidenceRefs:z.array(z.string()).default([]),detectionSignals:z.array(z.string()).default([]),recoveryActions:z.array(z.string()).default([]),recoveryEvidenceRefs:z.array(z.string()).default([]),singlePointOfFailure:z.boolean().default(false),status:z.enum(['OPEN','MITIGATED','ACCEPTED','UNKNOWN']).default('OPEN')});
export const failurePreventionModelSchema=z.object({systemId:z.string(),scenarios:z.array(failureScenarioSchema).default([]),criticalAssets:z.array(z.string()).default([])});
export const changePremortemSchema=z.object({model:failurePreventionModelSchema,changeSummary:z.string(),changedAssets:z.array(z.string()).default([]),rollbackAvailable:z.boolean().default(false),runtimeVerificationPlanned:z.boolean().default(false)});
export const compareFailureModelsSchema=z.object({before:failurePreventionModelSchema,after:failurePreventionModelSchema});
type FailureModel=z.infer<typeof failurePreventionModelSchema>;
export function runEngineeringPremortem(input:z.infer<typeof changePremortemSchema>){const matched=input.model.scenarios.filter(s=>s.affectedAssets.some(a=>input.changedAssets.includes(a))),hypotheses=[...(!input.rollbackAvailable?['Rollback unavailable for failed change.']:[]),...(!input.runtimeVerificationPlanned?['Runtime regression may remain undetected after deployment.']:[])];return{changeSummary:input.changeSummary,matchedScenarios:matched,hypotheses,hardStops:matched.filter(s=>s.severity==='CRITICAL'&&s.status!=='MITIGATED').map(s=>s.id),rule:'Pre-mortem findings are risk hypotheses, not predictions.'};}
export function detectSinglePointsOfFailure(m:FailureModel){return{singlePoints:m.scenarios.filter(s=>s.singlePointOfFailure).map(s=>s.id),criticalAssetsWithoutScenario:m.criticalAssets.filter(a=>!m.scenarios.some(s=>s.affectedAssets.includes(a)))};}
export function auditPreventiveControls(m:FailureModel){return{controlGaps:m.scenarios.filter(s=>!s.existingControls.length||!s.controlEvidenceRefs.length).map(s=>s.id),recoveryGaps:m.scenarios.filter(s=>sev[s.severity]>=3&&(!s.recoveryActions.length||!s.recoveryEvidenceRefs.length)).map(s=>s.id)};}
export function buildFailureDetectionMatrix(m:FailureModel){return{rows:m.scenarios.map(s=>({id:s.id,severity:s.severity,signals:s.detectionSignals,detectable:!!s.detectionSignals.length})),undetectableHighSeverity:m.scenarios.filter(s=>sev[s.severity]>=3&&!s.detectionSignals.length).map(s=>s.id)};}
export function evaluateResilienceReadiness(m:FailureModel){const a=auditPreventiveControls(m),openCritical=m.scenarios.filter(s=>s.severity==='CRITICAL'&&s.status==='OPEN').map(s=>s.id),blockers=uniq([...openCritical,...a.recoveryGaps]);return{status:blockers.length?'BLOCKED':a.controlGaps.length?'ATTENTION':'READY',blockers,audit:a};}
export function buildFailurePreventionPlan(m:FailureModel){return{readiness:evaluateResilienceReadiness(m),actions:m.scenarios.filter(s=>s.status==='OPEN'||s.status==='UNKNOWN').sort((a,b)=>sev[b.severity]-sev[a.severity]).map(s=>({id:s.id,severity:s.severity,actions:[...(!s.existingControls.length?['Define preventive control']:[]),...(!s.controlEvidenceRefs.length?['Collect control evidence']:[]),...(!s.detectionSignals.length?['Define detection signal']:[]),...(!s.recoveryActions.length?['Define recovery action']:[]),...(!s.recoveryEvidenceRefs.length?['Verify recovery path']:[])]}))};}
export function compareFailureModels(before:FailureModel,after:FailureModel){return{readiness:{before:evaluateResilienceReadiness(before),after:evaluateResilienceReadiness(after)},added:after.scenarios.filter(x=>!before.scenarios.some(y=>y.id===x.id)).map(x=>x.id),mitigated:after.scenarios.filter(x=>x.status==='MITIGATED'&&before.scenarios.some(y=>y.id===x.id&&y.status!=='MITIGATED')).map(x=>x.id)};}

export const decisionOptionSchema=z.object({id:z.string(),label:z.string(),constraintsViolated:z.array(z.string()).default([]),evidenceRefs:z.array(z.string()).default([]),reversible:z.boolean().default(true)});
export const engineeringDecisionSchema=z.object({decisionId:z.string(),title:z.string(),required:z.boolean().default(true),options:z.array(decisionOptionSchema).min(1),selectedOptionId:z.string().optional(),status:z.enum(['OPEN','PROPOSED','APPROVED','REJECTED','SUPERSEDED','UNKNOWN']).default('OPEN'),approver:z.string().optional(),evidenceRefs:z.array(z.string()).default([]),supersedes:z.array(z.string()).default([])});
export const decisionCommandModelSchema=z.object({projectId:z.string(),decisions:z.array(engineeringDecisionSchema).default([]),activeBlockers:z.array(z.object({id:z.string(),severity:z.enum(['CRITICAL','HIGH','MEDIUM','LOW']),description:z.string()})).default([]),releaseState:z.enum(['READY','CONDITIONAL','BLOCKED','UNKNOWN']).default('UNKNOWN'),runtimeState:z.enum(['HEALTHY','DEGRADED','INCIDENT','UNKNOWN']).default('UNKNOWN'),securityState:z.enum(['PASS','ATTENTION','BLOCKED','UNKNOWN']).default('UNKNOWN'),complianceState:z.enum(['PASS','ATTENTION','BLOCKED','UNKNOWN']).default('UNKNOWN'),evidenceFreshness:z.array(z.object({ref:z.string(),stale:z.boolean(),critical:z.boolean().default(false)})).default([])});
export const compareDecisionModelsSchema=z.object({before:decisionCommandModelSchema,after:decisionCommandModelSchema});
type DecisionModel=z.infer<typeof decisionCommandModelSchema>;
export function auditEngineeringDecisions(m:DecisionModel){const invalidSelection=m.decisions.filter(d=>d.selectedOptionId&&!d.options.some(o=>o.id===d.selectedOptionId)).map(d=>d.decisionId),unsupportedApproval=m.decisions.filter(d=>d.status==='APPROVED'&&(!d.approver||!d.evidenceRefs.length)).map(d=>d.decisionId),violated=m.decisions.filter(d=>d.status==='APPROVED'&&d.options.find(o=>o.id===d.selectedOptionId)?.constraintsViolated.length).map(d=>d.decisionId);return{healthy:!invalidSelection.length&&!unsupportedApproval.length&&!violated.length,invalidSelection,unsupportedApproval,approvedWithConstraintViolations:violated};}
export function evaluateDecision(d:z.infer<typeof engineeringDecisionSchema>){const selected=d.options.find(o=>o.id===d.selectedOptionId),blockers:string[]=[];if(d.required&&!selected)blockers.push('Required decision has no selected option.');if(d.status==='APPROVED'&&!d.approver)blockers.push('Approved decision has no approver.');if(d.status==='APPROVED'&&!d.evidenceRefs.length)blockers.push('Approved decision lacks evidence.');if(selected?.constraintsViolated.length)blockers.push('Selected option violates explicit constraints.');return{decisionId:d.decisionId,status:blockers.length?'BLOCKED':d.status,selected,options:d.options,blockers};}
export function detectDecisionConflicts(m:DecisionModel){return{supersessionConflicts:m.decisions.flatMap(d=>d.supersedes.filter(id=>m.decisions.some(x=>x.decisionId===id&&x.status==='APPROVED')).map(id=>({newDecision:d.decisionId,supersededDecision:id}))),duplicateTitles:uniq(m.decisions.map(d=>d.title).filter((x,i,a)=>a.indexOf(x)!==i))};}
export function buildDecisionRiskCommandCenter(m:DecisionModel){const criticalBlockers=m.activeBlockers.filter(x=>x.severity==='CRITICAL'),highBlockers=m.activeBlockers.filter(x=>x.severity==='HIGH'),staleCritical=m.evidenceFreshness.filter(x=>x.stale&&x.critical).map(x=>x.ref),stateConflicts:string[]=[];if(m.releaseState==='READY'&&m.securityState==='BLOCKED')stateConflicts.push('Release READY conflicts with Security BLOCKED.');if(m.releaseState==='READY'&&m.complianceState==='BLOCKED')stateConflicts.push('Release READY conflicts with Compliance BLOCKED.');if(m.releaseState==='READY'&&m.runtimeState==='INCIDENT')stateConflicts.push('Release READY conflicts with active runtime incident.');if(m.releaseState==='READY'&&staleCritical.length)stateConflicts.push('Release READY conflicts with stale critical evidence.');const audit=auditEngineeringDecisions(m);return{commandState:criticalBlockers.length||stateConflicts.length||!audit.healthy?'BLOCKED':highBlockers.length||m.runtimeState==='DEGRADED'?'ATTENTION':'READY',criticalBlockers,highBlockers,staleCriticalEvidence:staleCritical,stateConflicts,audit,openRequiredDecisions:m.decisions.filter(d=>d.required&&d.status!=='APPROVED').map(d=>d.decisionId)};}
export function buildDecisionEvidenceMatrix(m:DecisionModel){return{decisions:m.decisions.map(d=>({id:d.decisionId,status:d.status,decisionEvidence:d.evidenceRefs,selectedOptionEvidence:d.options.find(o=>o.id===d.selectedOptionId)?.evidenceRefs??[]}))};}
export function buildExecutiveEngineeringBrief(m:DecisionModel){const c=buildDecisionRiskCommandCenter(m);return{projectId:m.projectId,commandState:c.commandState,releaseState:m.releaseState,runtimeState:m.runtimeState,securityState:m.securityState,complianceState:m.complianceState,criticalBlockers:c.criticalBlockers.map(x=>x.id),stateConflicts:c.stateConflicts,openRequiredDecisions:c.openRequiredDecisions};}
export function compareDecisionModels(before:DecisionModel,after:DecisionModel){return{command:{before:buildDecisionRiskCommandCenter(before),after:buildDecisionRiskCommandCenter(after)},blockerDelta:after.activeBlockers.length-before.activeBlockers.length};}

export const enterpriseCommandSnapshotSchema=z.object({snapshotId:z.string(),projectId:z.string(),portfolio:portfolioModelSchema,pipeline:pipelineModelSchema,failurePrevention:failurePreventionModelSchema,decisionCommand:decisionCommandModelSchema,missionStatus:z.enum(['READY','IN_PROGRESS','BLOCKED','FAILED','COMPLETE','UNKNOWN']).default('UNKNOWN'),missionBlockers:z.array(z.string()).default([]),missionEvidenceRefs:z.array(z.string()).default([])});
export const compareEnterpriseSnapshotsSchema=z.object({before:enterpriseCommandSnapshotSchema,after:enterpriseCommandSnapshotSchema});
type Snapshot=z.infer<typeof enterpriseCommandSnapshotSchema>;
export function buildEnterpriseCommandSnapshot(s:Snapshot){return{snapshotId:s.snapshotId,projectId:s.projectId,mission:{status:s.missionStatus,blockers:s.missionBlockers,evidenceRefs:s.missionEvidenceRefs},portfolio:buildPortfolioCommandBrief(s.portfolio),pipeline:evaluatePipelineGate(s.pipeline),resilience:evaluateResilienceReadiness(s.failurePrevention),decisions:buildDecisionRiskCommandCenter(s.decisionCommand)};}
export function evaluateEnterpriseCommandGate(s:Snapshot){const p=auditPortfolio(s.portfolio),ci=evaluatePipelineGate(s.pipeline),r=evaluateResilienceReadiness(s.failurePrevention),d=buildDecisionRiskCommandCenter(s.decisionCommand),blockers=uniq([...s.missionBlockers,...(!p.healthy?['PORTFOLIO_INTEGRITY_GAP']:[]),...(ci.status==='BLOCKED'?ci.blockers.map(x=>`PIPELINE:${x}`):[]),...(r.status==='BLOCKED'?r.blockers.map(x=>`RESILIENCE:${x}`):[]),...(d.commandState==='BLOCKED'?[...d.stateConflicts.map(x=>`DECISION:${x}`),...d.criticalBlockers.map(x=>`DECISION_BLOCKER:${x.id}`)]:[])]);if(s.missionStatus==='COMPLETE'&&!s.missionEvidenceRefs.length)blockers.push('MISSION_COMPLETE_WITHOUT_EVIDENCE');return{status:blockers.length?'BLOCKED':ci.status==='PASS'&&r.status==='READY'&&d.commandState==='READY'?'READY':'ATTENTION',blockers,dimensions:{portfolio:p.healthy?'PASS':'ATTENTION',pipeline:ci.status,resilience:r.status,decisionCommand:d.commandState,mission:s.missionStatus}};}
export function selectEnterpriseIntervention(s:Snapshot){const gate=evaluateEnterpriseCommandGate(s),hardening=buildPipelineHardeningPlan(s.pipeline),prevention=buildFailurePreventionPlan(s.failurePrevention),command=buildDecisionRiskCommandCenter(s.decisionCommand),candidates=[...command.criticalBlockers.map(x=>({domain:'DECISION_COMMAND',severity:'CRITICAL',action:`Resolve blocker ${x.id}: ${x.description}`})),...prevention.actions.filter(x=>x.severity==='CRITICAL').map(x=>({domain:'RESILIENCE',severity:'CRITICAL',action:`Mitigate ${x.id}`})),...hardening.actions.map(action=>({domain:'PIPELINE',severity:'HIGH',action})),...command.openRequiredDecisions.map(id=>({domain:'DECISION_COMMAND',severity:'HIGH',action:`Resolve required engineering decision ${id}`}))];return{gateStatus:gate.status,nextIntervention:candidates[0]??null,candidates,rule:'Intervention order follows explicit blockers; consequential actions still require appropriate authorization.'};}
export function compareEnterpriseCommandSnapshots(before:Snapshot,after:Snapshot){const b=evaluateEnterpriseCommandGate(before),a=evaluateEnterpriseCommandGate(after);return{gate:{before:b.status,after:a.status},blockerDelta:a.blockers.length-b.blockers.length,resolvedBlockers:b.blockers.filter(x=>!a.blockers.includes(x)),newBlockers:a.blockers.filter(x=>!b.blockers.includes(x)),evidenceDelta:after.missionEvidenceRefs.length-before.missionEvidenceRefs.length};}
