import { z } from 'zod';

const severity=z.enum(['CRITICAL','HIGH','MEDIUM','LOW']);
const state=z.enum(['PASS','ATTENTION','BLOCKED','UNKNOWN']);
const uniq=<T,>(v:T[])=>[...new Set(v)];
const rank:{[k:string]:number}={CRITICAL:4,HIGH:3,MEDIUM:2,LOW:1,PASS:0,ATTENTION:2,BLOCKED:4,UNKNOWN:3};

const item=z.object({id:z.string(),kind:z.string().default('GENERIC'),status:z.string().default('UNKNOWN'),severity:severity.default('MEDIUM'),dependsOn:z.array(z.string()).default([]),evidenceRefs:z.array(z.string()).default([]),tags:z.array(z.string()).default([]),changed:z.boolean().default(false),authorized:z.boolean().default(false),requiresApproval:z.boolean().default(false),fresh:z.boolean().default(true),metadata:z.record(z.string(),z.unknown()).default({})});

export const semanticRouteSchema=z.object({request:z.string().min(1),intentTags:z.array(z.string()).default([]),constraints:z.array(z.string()).default([]),availableTools:z.array(z.string()).default([]),requiredEvidence:z.array(z.string()).default([]),authorizationBoundary:z.array(z.string()).default([]),alternateRequest:z.string().optional()});
export function normalizeIntent(x:z.infer<typeof semanticRouteSchema>){const text=x.request.toLowerCase();const inferred=uniq([...x.intentTags,...(['debug','error','fail'].some(k=>text.includes(k))?['DEBUG']:[]),...(['deploy','release','production'].some(k=>text.includes(k))?['RELEASE']:[]),...(['security','auth','rls'].some(k=>text.includes(k))?['SECURITY']:[]),...(['ui','ux','design'].some(k=>text.includes(k))?['UIUX']:[]),...(['test','coverage'].some(k=>text.includes(k))?['TEST']:[])]);return{request:x.request,intents:inferred,constraints:x.constraints,requiredEvidence:x.requiredEvidence,authorizationBoundary:x.authorizationBoundary};}
export function routeSemanticIntent(x:z.infer<typeof semanticRouteSchema>){const n=normalizeIntent(x);const map:{[k:string]:string[]}={DEBUG:['krom_create_debug_session','krom_next_debug_diagnostic'],RELEASE:['krom_evaluate_production_readiness','krom_decide_release'],SECURITY:['krom_evaluate_security_assessment','krom_audit_authorization'],UIUX:['krom_audit_ui','krom_review_ui_evidence'],TEST:['krom_evaluate_test_coverage','krom_build_regression_plan']};const suggested=uniq(n.intents.flatMap(i=>map[i]??[])).filter(t=>!x.availableTools.length||x.availableTools.includes(t));return{normalized:n,suggestedTools:suggested,unmappedIntents:n.intents.filter(i=>!map[i]),requiresClarification:!suggested.length&&n.intents.length===0};}
export function buildToolChain(x:z.infer<typeof semanticRouteSchema>){const r=routeSemanticIntent(x);return{chain:r.suggestedTools.map((tool,i)=>({step:i+1,tool,dependsOn:i?[r.suggestedTools[i-1]]:[],requiresEvidence:x.requiredEvidence.length>0})),authorizationBoundary:x.authorizationBoundary};}
export function detectRoutingAmbiguity(x:z.infer<typeof semanticRouteSchema>){const r=routeSemanticIntent(x);return{ambiguous:r.normalized.intents.length>3||r.unmappedIntents.length>0||r.requiresClarification,reasons:[...(r.normalized.intents.length>3?['Many competing intent domains']:[]),...(r.unmappedIntents.length?['Unmapped intent tags']:[]),...(r.requiresClarification?['No confident route']:[])]};}
export function validateRouteEvidence(x:z.infer<typeof semanticRouteSchema>){const consequential=/deploy|production|delete|migrate|security|permission/i.test(x.request);return{valid:!consequential||x.requiredEvidence.length>0,consequential,missing:consequential&&x.requiredEvidence.length===0?['requiredEvidence']:[],authorizationBoundary:x.authorizationBoundary};}
export function compareRoutes(x:z.infer<typeof semanticRouteSchema>){const a=routeSemanticIntent(x);const b=x.alternateRequest?routeSemanticIntent({...x,request:x.alternateRequest}):null;return{primary:a,alternate:b,toolDelta:b?{added:b.suggestedTools.filter(t=>!a.suggestedTools.includes(t)),removed:a.suggestedTools.filter(t=>!b.suggestedTools.includes(t))}:null};}

export const freshnessModelSchema=z.object({now:z.string().optional(),artifacts:z.array(z.object({id:z.string(),createdAt:z.string().optional(),maxAgeHours:z.number().nonnegative().optional(),fresh:z.boolean().default(true),dependsOn:z.array(z.string()).default([]),fingerprint:z.string().optional(),currentFingerprint:z.string().optional(),claimRefs:z.array(z.string()).default([])})).default([]),claims:z.array(z.object({id:z.string(),evidenceRefs:z.array(z.string()).default([]),status:z.string().default('UNKNOWN')})).default([]),previous:z.record(z.string(),z.unknown()).optional()});
export function auditEvidenceFreshness(x:z.infer<typeof freshnessModelSchema>){const stale=x.artifacts.filter(a=>!a.fresh||(a.fingerprint&&a.currentFingerprint&&a.fingerprint!==a.currentFingerprint)).map(a=>a.id);return{status:stale.length?'ATTENTION':'PASS',staleArtifacts:stale,freshArtifacts:x.artifacts.filter(a=>!stale.includes(a.id)).map(a=>a.id)};}
export function invalidateEvidence(x:z.infer<typeof freshnessModelSchema>){const audit=auditEvidenceFreshness(x);return{invalidated:audit.staleArtifacts,retained:audit.freshArtifacts,rule:'Fingerprint or freshness mismatch invalidates evidence support until reverified.'};}
export function buildReverificationPlan(x:z.infer<typeof freshnessModelSchema>){const inv=invalidateEvidence(x);return{actions:inv.invalidated.map(id=>({artifactId:id,action:'REVERIFY',dependentClaims:x.claims.filter(c=>c.evidenceRefs.includes(id)).map(c=>c.id)}))};}
export function detectStaleClaims(x:z.infer<typeof freshnessModelSchema>){const stale=new Set(auditEvidenceFreshness(x).staleArtifacts);return{staleClaims:x.claims.filter(c=>c.evidenceRefs.some(e=>stale.has(e))).map(c=>c.id),unsupportedClaims:x.claims.filter(c=>!c.evidenceRefs.length).map(c=>c.id)};}
export function computeEvidenceDependencies(x:z.infer<typeof freshnessModelSchema>){return{edges:x.artifacts.flatMap(a=>a.dependsOn.map(d=>({from:d,to:a.id,type:'EVIDENCE_DEPENDS_ON'}))),claimEdges:x.claims.flatMap(c=>c.evidenceRefs.map(e=>({from:e,to:c.id,type:'SUPPORTS'})))};}
export function compareFreshness(x:z.infer<typeof freshnessModelSchema>){return{current:auditEvidenceFreshness(x),previous:x.previous??null};}

export const changeImpactModelSchema=z.object({nodes:z.array(item).default([]),edges:z.array(z.object({from:z.string(),to:z.string(),type:z.string()})).default([]),changedIds:z.array(z.string()).default([]),previousChangedIds:z.array(z.string()).default([])});
function impacted(x:z.infer<typeof changeImpactModelSchema>){const seen=new Set(x.changedIds);let changed=true;while(changed){changed=false;for(const e of x.edges)if(seen.has(e.from)&&!seen.has(e.to)){seen.add(e.to);changed=true}}return [...seen];}
export function buildUnifiedChangeImpactGraph(x:z.infer<typeof changeImpactModelSchema>){return{changed:x.changedIds,impacted:impacted(x),edges:x.edges};}
export function traceChangeToTests(x:z.infer<typeof changeImpactModelSchema>){const s=new Set(impacted(x));return{tests:x.nodes.filter(n=>s.has(n.id)&&/test/i.test(n.kind)).map(n=>n.id)};}
export function traceChangeToRuntime(x:z.infer<typeof changeImpactModelSchema>){const s=new Set(impacted(x));return{runtimeChecks:x.nodes.filter(n=>s.has(n.id)&&/runtime|deploy|health|slo/i.test(n.kind)).map(n=>n.id)};}
export function buildReverificationSet(x:z.infer<typeof changeImpactModelSchema>){const s=new Set(impacted(x));return{reverify:x.nodes.filter(n=>s.has(n.id)).map(n=>({id:n.id,kind:n.kind,evidenceRefs:n.evidenceRefs,needsEvidence:!n.evidenceRefs.length}))};}
export function detectUncoveredImpact(x:z.infer<typeof changeImpactModelSchema>){const r=buildReverificationSet(x).reverify;return{uncovered:r.filter(n=>n.needsEvidence).map(n=>n.id),covered:r.filter(n=>!n.needsEvidence).map(n=>n.id)};}
export function compareChangeImpacts(x:z.infer<typeof changeImpactModelSchema>){const now=new Set(impacted(x));const before=new Set(x.previousChangedIds);return{newlyImpacted:[...now].filter(i=>!before.has(i)),previousChanged:x.previousChangedIds};}

export const workflowModelSchema=z.object({workflowId:z.string().default('workflow'),intentTags:z.array(z.string()).default([]),templates:z.array(z.object({id:z.string(),tags:z.array(z.string()).default([]),phases:z.array(z.object({id:z.string(),requiresEvidence:z.boolean().default(false),requiresApproval:z.boolean().default(false),status:z.enum(['PENDING','READY','BLOCKED','COMPLETE']).default('PENDING')})).default([])})).default([]),selectedTemplateId:z.string().optional(),currentPhaseId:z.string().optional(),evidenceRefs:z.array(z.string()).default([]),approvals:z.array(z.string()).default([]),previous:z.record(z.string(),z.unknown()).optional()});
export function createWorkflowTemplate(x:z.infer<typeof workflowModelSchema>){return{workflowId:x.workflowId,templates:x.templates,rule:'Templates define orchestration contracts only; they do not execute host actions.'};}
export function selectWorkflowTemplate(x:z.infer<typeof workflowModelSchema>){const scored=x.templates.map(t=>({id:t.id,score:t.tags.filter(tag=>x.intentTags.includes(tag)).length})).sort((a,b)=>b.score-a.score);return{selected:scored[0]??null,candidates:scored};}
export function instantiateWorkflow(x:z.infer<typeof workflowModelSchema>){const id=x.selectedTemplateId??selectWorkflowTemplate(x).selected?.id;const t=x.templates.find(t=>t.id===id);return{workflowId:x.workflowId,templateId:id??null,phases:t?.phases??[],currentPhaseId:t?.phases[0]?.id??null};}
export function validateWorkflow(x:z.infer<typeof workflowModelSchema>){const inst=instantiateWorkflow(x);const ids=inst.phases.map(p=>p.id);return{valid:!!inst.templateId&&new Set(ids).size===ids.length,missingTemplate:!inst.templateId,duplicatePhases:ids.filter((id,i)=>ids.indexOf(id)!==i)};}
export function advanceWorkflowState(x:z.infer<typeof workflowModelSchema>){const inst=instantiateWorkflow(x);const idx=Math.max(0,inst.phases.findIndex(p=>p.id===x.currentPhaseId));const phase=inst.phases[idx];const blocked=!!phase&&((phase.requiresEvidence&&!x.evidenceRefs.length)||(phase.requiresApproval&&!x.approvals.length));return{current:phase?.id??null,status:blocked?'BLOCKED':'ADVANCE_ALLOWED',next:blocked?null:inst.phases[idx+1]?.id??null};}
export function compareWorkflows(x:z.infer<typeof workflowModelSchema>){return{current:instantiateWorkflow(x),previous:x.previous??null};}

export const auditPackageSchema=z.object({packageId:z.string(),evidence:z.array(z.object({id:z.string(),domain:z.string(),claimRefs:z.array(z.string()).default([]),verified:z.boolean().default(false)})).default([]),approvals:z.array(z.object({id:z.string(),actionId:z.string(),approver:z.string().optional(),approved:z.boolean().default(false)})).default([]),exceptions:z.array(z.object({id:z.string(),status:z.enum(['ACTIVE','EXPIRED','CLOSED','PROPOSED']),evidenceRefs:z.array(z.string()).default([]),compensatingControls:z.array(z.string()).default([])})).default([]),releases:z.array(z.object({id:z.string(),evidenceRefs:z.array(z.string()).default([]),verified:z.boolean().default(false)})).default([]),previous:z.record(z.string(),z.unknown()).optional()});
export function buildEnterpriseAuditPackage(x:z.infer<typeof auditPackageSchema>){return{packageId:x.packageId,evidenceCount:x.evidence.length,approvals:x.approvals,releases:x.releases,exceptions:x.exceptions,index:buildEvidenceIndex(x)};}
export function validateAuditPackage(x:z.infer<typeof auditPackageSchema>){const missingEvidence=x.evidence.filter(e=>!e.verified).map(e=>e.id),badApprovals=x.approvals.filter(a=>a.approved&&!a.approver).map(a=>a.id),invalidExceptions=x.exceptions.filter(e=>e.status==='ACTIVE'&&(!e.evidenceRefs.length||!e.compensatingControls.length)).map(e=>e.id),unverifiedReleases=x.releases.filter(r=>!r.verified||!r.evidenceRefs.length).map(r=>r.id);return{status:missingEvidence.length||badApprovals.length||invalidExceptions.length||unverifiedReleases.length?'ATTENTION':'PASS',missingEvidence,badApprovals,invalidExceptions,unverifiedReleases};}
export function buildEvidenceIndex(x:z.infer<typeof auditPackageSchema>){return{byDomain:Object.fromEntries(uniq(x.evidence.map(e=>e.domain)).map(d=>[d,x.evidence.filter(e=>e.domain===d).map(e=>e.id)])),byClaim:x.evidence.flatMap(e=>e.claimRefs.map(c=>({claim:c,evidence:e.id})))};}
export function buildApprovalLedger(x:z.infer<typeof auditPackageSchema>){return{entries:x.approvals.map(a=>({id:a.id,actionId:a.actionId,approved:a.approved,approver:a.approver??null})),unsupportedApprovals:x.approvals.filter(a=>a.approved&&!a.approver).map(a=>a.id)};}
export function buildExceptionRegister(x:z.infer<typeof auditPackageSchema>){return{active:x.exceptions.filter(e=>e.status==='ACTIVE'),expired:x.exceptions.filter(e=>e.status==='EXPIRED'),proposed:x.exceptions.filter(e=>e.status==='PROPOSED')};}
export function compareAuditPackages(x:z.infer<typeof auditPackageSchema>){return{current:validateAuditPackage(x),previous:x.previous??null};}

export const releaseTrainModelSchema=z.object({trainId:z.string(),units:z.array(z.object({id:z.string(),severity:severity.default('MEDIUM'),status:state.default('UNKNOWN'),dependsOn:z.array(z.string()).default([]),environment:z.string().default('production'),rollbackReady:z.boolean().default(false),evidenceRefs:z.array(z.string()).default([]),window:z.string().optional()})).default([]),previous:z.record(z.string(),z.unknown()).optional()});
function trainOrder(x:z.infer<typeof releaseTrainModelSchema>){const out:string[]=[],done=new Set<string>();for(let i=0;i<x.units.length+1;i++)for(const u of x.units)if(!done.has(u.id)&&u.dependsOn.every(d=>done.has(d))){out.push(u.id);done.add(u.id)}return{order:out,cyclic:x.units.filter(u=>!done.has(u.id)).map(u=>u.id)};}
export function buildEnterpriseReleaseTrain(x:z.infer<typeof releaseTrainModelSchema>){return{trainId:x.trainId,...trainOrder(x),waves:trainOrder(x).order.map((id,i)=>({wave:i+1,unitId:id}))};}
export function detectReleaseTrainConflicts(x:z.infer<typeof releaseTrainModelSchema>){const ids=x.units.map(u=>u.id),dangling=x.units.flatMap(u=>u.dependsOn.filter(d=>!ids.includes(d)).map(d=>`${u.id}->${d}`));return{danglingDependencies:dangling,cyclic:trainOrder(x).cyclic,blockedUnits:x.units.filter(u=>u.status==='BLOCKED').map(u=>u.id)};}
export function evaluateTrainReadiness(x:z.infer<typeof releaseTrainModelSchema>){const c=detectReleaseTrainConflicts(x),unsupported=x.units.filter(u=>u.status==='PASS'&&!u.evidenceRefs.length).map(u=>u.id),rollbackGaps=x.units.filter(u=>u.environment==='production'&&!u.rollbackReady).map(u=>u.id),blockers=uniq([...c.danglingDependencies,...c.cyclic,...c.blockedUnits,...unsupported,...rollbackGaps]);return{status:blockers.length?'BLOCKED':'READY',blockers};}
export function buildCanarySequence(x:z.infer<typeof releaseTrainModelSchema>){return{sequence:[...x.units].sort((a,b)=>rank[a.severity]-rank[b.severity]).map((u,i)=>({step:i+1,unitId:u.id,severity:u.severity}))};}
export function buildRollbackMatrix(x:z.infer<typeof releaseTrainModelSchema>){return{rows:x.units.map(u=>({unitId:u.id,rollbackReady:u.rollbackReady,dependsOn:u.dependsOn,evidenceRefs:u.evidenceRefs})),gaps:x.units.filter(u=>!u.rollbackReady).map(u=>u.id)};}
export function compareReleaseTrains(x:z.infer<typeof releaseTrainModelSchema>){return{current:{readiness:evaluateTrainReadiness(x),order:trainOrder(x)},previous:x.previous??null};}

export const projectHealthModelSchema=z.object({projectId:z.string(),domains:z.array(z.object({name:z.string(),status:state,evidenceRefs:z.array(z.string()).default([]),blockers:z.array(z.string()).default([])})).default([]),runtimeIncident:z.boolean().default(false),releaseReady:z.boolean().default(false),previous:z.record(z.string(),z.unknown()).optional()});
export function detectHealthContradictions(x:z.infer<typeof projectHealthModelSchema>){const blocked=x.domains.filter(d=>d.status==='BLOCKED').map(d=>d.name),unknown=x.domains.filter(d=>d.status==='UNKNOWN').map(d=>d.name),contradictions:string[]=[];if(x.releaseReady&&blocked.length)contradictions.push('releaseReady conflicts with blocked domains');if(x.releaseReady&&x.runtimeIncident)contradictions.push('releaseReady conflicts with active runtime incident');return{blocked,unknown,contradictions};}
export function evaluateProjectHealthGate(x:z.infer<typeof projectHealthModelSchema>){const c=detectHealthContradictions(x),unsupported=x.domains.filter(d=>d.status==='PASS'&&!d.evidenceRefs.length).map(d=>d.name),blockers=uniq([...c.blocked,...c.contradictions,...unsupported]);return{status:blockers.length?'BLOCKED':c.unknown.length?'UNKNOWN':'PASS',blockers,unknown:c.unknown};}
export function buildProjectHealthSnapshot(x:z.infer<typeof projectHealthModelSchema>){return{projectId:x.projectId,gate:evaluateProjectHealthGate(x),domains:x.domains,runtimeIncident:x.runtimeIncident,releaseReady:x.releaseReady};}
export function buildHealthActionQueue(x:z.infer<typeof projectHealthModelSchema>){return{actions:x.domains.flatMap(d=>[...d.blockers.map(b=>({domain:d.name,severity:d.status==='BLOCKED'?'CRITICAL':'HIGH',action:b})),...(!d.evidenceRefs.length?[{domain:d.name,severity:'HIGH',action:'Collect/verify evidence'}]:[])])};}
export function buildExecutiveHealthBrief(x:z.infer<typeof projectHealthModelSchema>){const g=evaluateProjectHealthGate(x);return{projectId:x.projectId,status:g.status,blockedDomains:x.domains.filter(d=>d.status==='BLOCKED').map(d=>d.name),unknownDomains:g.unknown,evidenceGaps:x.domains.filter(d=>!d.evidenceRefs.length).map(d=>d.name),runtimeIncident:x.runtimeIncident,releaseReady:x.releaseReady};}
export function compareHealthSnapshots(x:z.infer<typeof projectHealthModelSchema>){return{current:buildProjectHealthSnapshot(x),previous:x.previous??null};}

export const autonomyModelSchema=z.object({actions:z.array(z.object({id:z.string(),kind:z.string(),severity:severity.default('MEDIUM'),readOnly:z.boolean().default(false),reversible:z.boolean().default(true),requiresApproval:z.boolean().default(false),approved:z.boolean().default(false),capabilityAvailable:z.boolean().default(false),evidenceRefs:z.array(z.string()).default([]),preconditions:z.array(z.object({id:z.string(),satisfied:z.boolean()}).default({id:'',satisfied:false})).default([])})).default([]),previous:z.record(z.string(),z.unknown()).optional()});
export function validateActionPreconditions(x:z.infer<typeof autonomyModelSchema>){return{actions:x.actions.map(a=>({id:a.id,missing:a.preconditions.filter(p=>!p.satisfied).map(p=>p.id),capabilityAvailable:a.capabilityAvailable}))};}
export function classifyNextAuthorizedAction(x:z.infer<typeof autonomyModelSchema>){const assessed=x.actions.map(a=>{const missing=a.preconditions.filter(p=>!p.satisfied).map(p=>p.id);const status=!a.capabilityAvailable||missing.length?'BLOCKED':a.requiresApproval&&!a.approved?'REQUIRE_APPROVAL':a.readOnly||a.reversible?'AUTO_EXECUTE':'REQUIRE_APPROVAL';return{id:a.id,status,missing};});return{next:assessed.find(a=>a.status==='AUTO_EXECUTE')??assessed.find(a=>a.status==='REQUIRE_APPROVAL')??assessed[0]??null,assessed};}
export function buildAuthorizationQueue(x:z.infer<typeof autonomyModelSchema>){const a=classifyNextAuthorizedAction(x).assessed;return{auto:a.filter(i=>i.status==='AUTO_EXECUTE'),approval:a.filter(i=>i.status==='REQUIRE_APPROVAL'),blocked:a.filter(i=>i.status==='BLOCKED')};}
export function enforceEvidenceBeforeAction(x:z.infer<typeof autonomyModelSchema>){const blocked=x.actions.filter(a=>a.severity==='CRITICAL'&&!a.evidenceRefs.length).map(a=>a.id);return{status:blocked.length?'BLOCKED':'PASS',blocked,rule:'Critical consequential actions require explicit evidence before execution.'};}
export function buildAutonomyRunbook(x:z.infer<typeof autonomyModelSchema>){const q=buildAuthorizationQueue(x);return{readOnly:x.actions.filter(a=>a.readOnly).map(a=>a.id),reversible:x.actions.filter(a=>a.reversible&&!a.readOnly).map(a=>a.id),approval:q.approval.map(a=>a.id),blocked:q.blocked.map(a=>a.id),evidenceGate:enforceEvidenceBeforeAction(x)};}
export function compareAutonomyStates(x:z.infer<typeof autonomyModelSchema>){return{current:{queue:buildAuthorizationQueue(x),evidenceGate:enforceEvidenceBeforeAction(x)},previous:x.previous??null};}
