import type { z } from 'zod';
import { performanceSnapshotSchema, performanceBudgetSchema, costGuardrailSchema } from './performance-cost-schema';
type Snapshot=z.infer<typeof performanceSnapshotSchema>; type Budget=z.infer<typeof performanceBudgetSchema>; type Cost=z.infer<typeof costGuardrailSchema>;
export function evaluatePerformanceBudgets(input:Budget){const checks=input.snapshot.metrics.map(m=>({name:m.name,status:m.budget==null?'UNKNOWN':m.value<=m.budget?'PASS':'FAIL',value:m.value,budget:m.budget,unit:m.unit,evidenceRef:m.evidenceRef}));const failures=checks.filter(c=>c.status==='FAIL');return{status:failures.length&&input.failOnBudgetExceeded?'FAIL':checks.some(c=>c.status==='UNKNOWN')?'PASS_WITH_GAPS':'PASS',checks,failures:failures.map(f=>f.name)};}
export function analyzeRuntimeCost(input:Snapshot){const known=input.resources.filter(r=>r.estimatedCost!=null);const total=known.reduce((s,r)=>s+(r.estimatedCost??0),0);const currency=known[0]?.currency??'USD';return{knownResourceCount:known.length,totalEstimatedCost:total,currency,unknownCostResources:input.resources.filter(r=>r.estimatedCost==null).map(r=>r.name),boundary:'Cost is an estimate derived only from supplied host data.'};}
export function enforceCostGuardrail(input:Cost){const cost=analyzeRuntimeCost(input.snapshot);const pct=input.monthlyBudget?cost.totalEstimatedCost/input.monthlyBudget*100:0;return{status:pct>100?'BLOCKED':pct>=input.warningPercent?'WARNING':'WITHIN_BUDGET',percentOfBudget:Math.round(pct*100)/100,budget:input.monthlyBudget,estimated:cost.totalEstimatedCost,currency:input.currency};}
export function detectPerformanceRegression(before:Snapshot,after:Snapshot){const b=new Map(before.metrics.map(m=>[m.name,m]));const regressions=after.metrics.filter(m=>b.has(m.name)&&m.value>(b.get(m.name)!.value)).map(m=>({name:m.name,before:b.get(m.name)!.value,after:m.value,delta:m.value-b.get(m.name)!.value,unit:m.unit}));return{regressions,regressionDetected:Boolean(regressions.length)};}
export function recommendPerformanceActions(input:Snapshot){const actions:string[]=[];for(const m of input.metrics){if(m.budget!=null&&m.value>m.budget)actions.push(`Reduce ${m.name}; observed ${m.value}${m.unit} exceeds ${m.budget}${m.unit}.`);}if((input.bundleBytes??0)>1_000_000)actions.push('Review client bundle splitting and dependency weight.');if((input.buildSeconds??0)>300)actions.push('Inspect build bottlenecks and cacheability.');return{actions:actions.length?actions:['No evidence-backed optimization action identified from supplied metrics.']};}
export function comparePerformanceSnapshots(before:Snapshot,after:Snapshot){return detectPerformanceRegression(before,after);}
