import type { z } from 'zod';import { planningModelSchema,executionSelectionSchema } from './planning-intelligence-schema';
type Plan=z.infer<typeof planningModelSchema>;type Exec=z.infer<typeof executionSelectionSchema>;
const weight:Record<string,number>={CRITICAL:4,HIGH:3,MEDIUM:2,LOW:1};
export function buildExecutionGraph(p:Plan){const ids=new Set(p.items.map(i=>i.id));const dangling=p.items.flatMap(i=>i.dependencies.filter(d=>!ids.has(d)).map(d=>({item:i.id,missing:d})));const incoming=new Map(p.items.map(i=>[i.id,i.dependencies.filter(d=>ids.has(d)).length]));const q=[...incoming].filter(([,n])=>n===0).map(([id])=>id);const order:string[]=[];while(q.length){const id=q.shift()!;order.push(id);for(const item of p.items.filter(i=>i.dependencies.includes(id))){incoming.set(item.id,(incoming.get(item.id)??0)-1);if(incoming.get(item.id)===0)q.push(item.id);}}return{order,cycleDetected:order.length!==p.items.length,danglingDependencies:dangling,status:dangling.length||order.length!==p.items.length?'BLOCKED':'READY'};}
export function evaluatePlanIntelligence(p:Plan){const graph=buildExecutionGraph(p);const gaps:string[]=[];for(const i of p.items){if(!i.acceptanceCriteria.length)gaps.push(`${i.id}: missing acceptance criteria`);if(!i.evidenceRequired.length)gaps.push(`${i.id}: missing evidence requirements`);}if(p.assumptions.length&&!p.riskNotes.length)gaps.push('Assumptions exist without explicit risk notes.');return{status:graph.status==='BLOCKED'?'BLOCKED':gaps.length?'READY_WITH_GAPS':'READY',graph,gaps,priorityScore:p.items.reduce((s,i)=>s+weight[i.priority],0)};}
export function selectNextPlanAction(input:Exec){const done=new Set(input.completedIds),failed=new Set(input.failedIds);const candidates=input.plan.items.filter(i=>!done.has(i.id)&&!failed.has(i.id)&&i.dependencies.every(d=>done.has(d))).sort((a,b)=>weight[b.priority]-weight[a.priority]);return candidates.length?{status:'READY',next:candidates[0],alternates:candidates.slice(1,4)}:{status:input.plan.items.every(i=>done.has(i.id))?'COMPLETE':'BLOCKED',next:null,blockers:input.plan.items.filter(i=>!done.has(i.id)).map(i=>({id:i.id,unmet:i.dependencies.filter(d=>!done.has(d))}))};}
export function detectPlanConflicts(p:Plan){const conflicts=p.items.filter(i=>i.dependencies.includes(i.id)).map(i=>({item:i.id,reason:'self-dependency'}));return{conflicts,status:conflicts.length?'CONFLICT':'CLEAR'};}
export function createPlanEvidenceMatrix(p:Plan){return{rows:p.items.map(i=>({id:i.id,title:i.title,acceptanceCriteria:i.acceptanceCriteria,evidenceRequired:i.evidenceRequired,status:i.status})),coverage:{withAcceptance:p.items.filter(i=>i.acceptanceCriteria.length).length,total:p.items.length,withEvidence:p.items.filter(i=>i.evidenceRequired.length).length}};}
export function comparePlans(before:Plan,after:Plan){const b=new Set(before.items.map(i=>i.id)),a=new Set(after.items.map(i=>i.id));return{added:[...a].filter(x=>!b.has(x)),removed:[...b].filter(x=>!a.has(x)),before:evaluatePlanIntelligence(before),after:evaluatePlanIntelligence(after)};}
