import type { V63TrustInput } from './v63-schema';
const uniq=<T>(xs:T[])=>[...new Set(xs)];
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
export function buildAttestationChainV63(i:V63TrustInput){return{chains:i.evidence.map(e=>({evidenceId:e.id,parents:e.parentIds,attestations:i.attestations.filter(a=>a.evidenceId===e.id).map(a=>a.id)})),signatureClaim:false};}
export function scoreProvenanceTrustV63(i:V63TrustInput){return{evidence:i.evidence.map(e=>{const at=i.attestations.filter(a=>a.evidenceId===e.id&&a.verified);const score=clamp((e.verified?35:0)+(e.fresh?20:0)+e.confidence*.3+Math.min(at.length*10,20));return{id:e.id,score:Number(score.toFixed(2))}}).sort((a,b)=>b.score-a.score)};}
export function simulateGovernancePoliciesV63(i:V63TrustInput){const p=[...i.policies].sort((a,b)=>b.priority-a.priority);return{changes:i.changes.map(c=>{const r=p.find(x=>x.actionKind==='*'||x.actionKind===c.kind);return{id:c.id,effect:r?.effect??'ALLOW',simulated:true,executed:false};})};}
export function buildChangeAuthorizationEnvelopesV63(i:V63TrustInput){const valid=new Set(i.evidence.filter(e=>e.verified&&e.fresh).map(e=>e.id));return{changes:i.changes.map(c=>({id:c.id,evidenceReady:c.evidenceRefs.length>0&&c.evidenceRefs.every(e=>valid.has(e)),separationOk:!c.requester||!c.approver||c.requester!==c.approver,authorized:false}))};}
export function checkSegregationOfDutiesV63(i:V63TrustInput){return{violations:i.changes.filter(c=>c.requester&&c.approver&&c.requester===c.approver).map(c=>c.id)};}
export function evaluateApprovalQuorumV63(i:V63TrustInput){return{actions:uniq(i.approvals.map(a=>a.actionId)).map(actionId=>{const voters=uniq(i.approvals.filter(a=>a.actionId===actionId&&a.approved).map(a=>a.actorId));return{actionId,count:voters.length,required:i.requiredApprovalCount,quorum:voters.length>=i.requiredApprovalCount};})};}
export function mapComplianceControlsV63(i:V63TrustInput){const eids=new Set(i.evidence.map(e=>e.id));return{controls:i.controls.map(c=>({id:c.id,framework:c.framework,covered:c.evidenceRefs.length>0&&c.evidenceRefs.every(e=>eids.has(e)),missing:c.evidenceRefs.filter(e=>!eids.has(e))}))};}
export function evaluateWaiverGovernanceV63(i:V63TrustInput){return{waivers:i.waivers.map(w=>({id:w.id,controlId:w.controlId,active:w.approved&&(w.expires===undefined||w.expires>i.nowEpoch),expired:w.expires!==undefined&&w.expires<=i.nowEpoch}))};}
export function propagateEvidenceFreshnessInvalidationV63(i:V63TrustInput){const stale=new Set(i.evidence.filter(e=>!e.fresh).map(e=>e.id));let changed=true;while(changed){changed=false;for(const e of i.evidence)if(e.parentIds.some(p=>stale.has(p))&&!stale.has(e.id)){stale.add(e.id);changed=true}}return{stale:[...stale]};}
export function verifyArtifactIntegrityContractsV63(i:V63TrustInput){return{artifacts:i.artifacts.map(a=>({id:a.id,integrity:a.expectedHash? a.hash===a.expectedHash&&a.verified : a.verified,signatureVerified:false}))};}
export function compileGovernanceAuditTrailV63(i:V63TrustInput){return{entries:[...i.changes.map(c=>({type:'CHANGE',id:c.id})),...i.approvals.map(a=>({type:'APPROVAL',id:a.id})),...i.waivers.map(w=>({type:'WAIVER',id:w.id}))],persistenceClaim:false};}
export function scoreRuntimeTrustV63(i:V63TrustInput){const p=scoreProvenanceTrustV63(i).evidence;const avg=p.length?p.reduce((s,x)=>s+x.score,0)/p.length:0;const sod=checkSegregationOfDutiesV63(i).violations.length;const integrity=verifyArtifactIntegrityContractsV63(i).artifacts;const ok=integrity.length?integrity.filter(a=>a.integrity).length/integrity.length:1;return{score:Number(clamp(avg-sod*15-(1-ok)*25).toFixed(2)),evidenceAverage:Number(avg.toFixed(2)),sodViolations:sod,artifactIntegrityRate:Number((ok*100).toFixed(2))};}
export function analyzeDeploymentAuthorizationV63(i:V63TrustInput){const q=new Map(evaluateApprovalQuorumV63(i).actions.map(a=>[a.actionId,a]));const auth=buildChangeAuthorizationEnvelopesV63(i).changes;return{releases:i.releases.map(r=>({id:r.id,authorized:r.changeIds.every(id=>auth.find(c=>c.id===id)?.evidenceReady)&&r.changeIds.every(id=>(q.get(id)?.quorum??false)),executed:false}))};}
export function buildReleaseGovernancePacketsV63(i:V63TrustInput){return{packets:i.releases.map(r=>({releaseId:r.id,risk:r.risk,changes:r.changeIds,authorization:analyzeDeploymentAuthorizationV63(i).releases.find(x=>x.id===r.id)?.authorized??false,trust:scoreRuntimeTrustV63(i).score,complianceMapped:mapComplianceControlsV63(i).controls.every(c=>c.covered)}))};}
export function evaluateExceptionRiskV63(i:V63TrustInput){const active=evaluateWaiverGovernanceV63(i).waivers.filter(w=>w.active);return{activeWaivers:active.map(w=>w.id),riskPenalty:Math.min(40,active.length*10)};}
export function auditAttestationCompletenessV63(i:V63TrustInput){const by=new Set(i.attestations.filter(a=>a.verified&&a.signatureObserved).map(a=>a.evidenceId));return{attested:i.evidence.filter(e=>by.has(e.id)).map(e=>e.id),unattested:i.evidence.filter(e=>!by.has(e.id)).map(e=>e.id)};}
export function evaluateControlEvidenceSufficiencyV63(i:V63TrustInput){const verified=new Set(i.evidence.filter(e=>e.verified&&e.fresh).map(e=>e.id));return{controls:i.controls.map(c=>({id:c.id,sufficient:c.evidenceRefs.length>0&&c.evidenceRefs.every(e=>verified.has(e))}))};}
export function buildGovernanceHealthV63(i:V63TrustInput){return{trust:scoreRuntimeTrustV63(i),sod:checkSegregationOfDutiesV63(i).violations.length,stale:propagateEvidenceFreshnessInvalidationV63(i).stale.length,unattested:auditAttestationCompletenessV63(i).unattested.length,activeWaivers:evaluateExceptionRiskV63(i).activeWaivers.length};}
export function auditTrustGovernanceConsistencyV63(i:V63TrustInput){const eids=new Set(i.evidence.map(e=>e.id));const cids=new Set(i.controls.map(c=>c.id));const actorIds=new Set(i.actors.map(a=>a.id));return{unknownEvidenceParents:uniq(i.evidence.flatMap(e=>e.parentIds).filter(x=>!eids.has(x))),unknownAttestationEvidence:uniq(i.attestations.map(a=>a.evidenceId).filter(x=>!eids.has(x))),unknownWaiverControls:uniq(i.waivers.map(w=>w.controlId).filter(x=>!cids.has(x))),unknownApprovalActors:uniq(i.approvals.map(a=>a.actorId).filter(x=>!actorIds.has(x)))};}
export function buildTrustGovernanceSnapshotV63(i:V63TrustInput){const consistency=auditTrustGovernanceConsistencyV63(i);return{attestation:buildAttestationChainV63(i),provenance:scoreProvenanceTrustV63(i),policy:simulateGovernancePoliciesV63(i),authorization:analyzeDeploymentAuthorizationV63(i),release:buildReleaseGovernancePacketsV63(i),health:buildGovernanceHealthV63(i),consistency,status:Object.values(consistency).every(v=>v.length===0)?'READY':'BLOCKED',executionClaim:false,persistenceClaim:false,certificationClaim:false};}
export function buildGovernanceOperatorBriefV63(i:V63TrustInput){const s=buildTrustGovernanceSnapshotV63(i);return{status:s.status,trust:s.health.trust.score,blockingSoD:s.health.sod,staleEvidence:s.health.stale,unattestedEvidence:s.health.unattested,releaseAuthorizations:s.authorization.releases,evidenceBoundary:'No signatures, approvals, certification, persistence or deployment are inferred beyond supplied evidence.'};}
